### ISSUE TITLE
v0.0.2 Sprint

### ISSUE THREAD

**Issue by Jamesford** [Wiredcraft/dashy#52]
The goals for the next release of Dashy are as follows:
- **Admin UI**:
  - [x] Add Widget
    - [x] FIX: If no source, widget breaks
  - [x] Update Widget (#49 & #48 )
  - [x] Delete Widget (#49)
- **Widgets**
  - [x] Add update/delete buttons to each widget (#49)
- **Deploy**
  - [x] Deploy Dashy + CouchDB onto a server (#28)
    - Moved to backlog
- **Documentation**
  - [x] Keep documentation up to date for v0.0.2 (#47)
